---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "{{ .Values.istio.sidecarInjection }}"
        {{- if .Values.istio.sidecarInjection }}
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
        {{- end }}
        {{- if .Values.istio.envoyStatsInclusionPrefixes }}
        sidecar.istio.io/statsInclusionPrefixes: "{{ .Values.istio.envoyStatsInclusionPrefixes }}"
        {{- end }}
        {{- if .Values.istio.sidecarCpuLimit }}
        sidecar.istio.io/proxyCPULimit: "{{ .Values.istio.sidecarCpuLimit }}"
        {{- end }}
        {{- if .Values.istio.sidecarConcurrency }}
        proxy.istio.io/config: "{{ .Values.istio.sidecarConcurrency }}"
        {{- end }}
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      serviceAccountName: {{ .Values.deployment.name }}
      containers:
        - name: fortio
          image: fortio/fortio:latest_release
          imagePullPolicy: {{ .Values.deployment.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http-fortio
            - containerPort: 8079
              name: grpc-ping
          volumeMounts:
            - name: {{ .Values.deployment.name }}-storage
              mountPath: /var/lib/fortio
          {{- if .Values.deployment.resources }}
          resources:
          {{- toYaml .Values.deployment.resources | nindent 12 }}
          {{- end }}
        - name: shell
          image: bash:5.1.4
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1
          volumeMounts:
            - name: {{ .Values.deployment.name }}-storage
              mountPath: /var/lib/fortio
          args: ["/bin/sleep", "infinity"]
      {{- if .Values.deployment.affinity }}
      affinity:
        {{- if .Values.deployment.affinity.nodeAffinity }}
        nodeAffinity:
        {{- toYaml .Values.deployment.affinity.nodeAffinity | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.affinity.podAffinity }}
        podAffinity:
        {{- toYaml .Values.deployment.affinity.podAffinity | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.affinity.podAntiAffinity }}
        podAntiAffinity:
        {{- toYaml .Values.deployment.affinity.podAntiAffinity | nindent 10 }}
        {{- end }}
      {{- end }}
      {{- if .Values.deployment.tolerations }}
      tolerations:
      {{- toYaml .Values.deployment.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.deployment.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.deployment.nodeSelector | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.deployment.name }}-storage
          persistentVolumeClaim:
            claimName: {{ .Values.deployment.name }}
