---
{{- if and (.Values.istio.sidecarInjection) (not .Values.istio.mtls) }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: "default"
  namespace: {{ .Values.deployment.namespace }}
spec:
  mtls:
    mode: DISABLE
{{- end }}
