---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: {{ .Values.deployment.name }}
spec:
  ports:
  - port: 8080
    name: http
    targetPort: http-fortio
  - port: 8079
    name: http2
    targetPort: grpc-ping
  selector:
    app: {{ .Values.deployment.name }}
