apiVersion: v2
appVersion: 1.0.0
description: A Helm chart for fortio, an istio load testing tool
engine: gotpl
keywords:
  - istio
  - aspenmesh
  - performance
  - benchmark
  - golang
  - fortio
maintainers:
  - name: Bart Van Bos
    email: bartvanbos@gmail.com
name: fortio-client
sources: 
  - https://github.com/fortio/fortio
type: application
version: 1.0.0
